[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_counter = "Cg4JMX7ut5z52Q7n3mhs3twBb3WyyGPSbgGZiAEqxywb"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/tarun/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
