[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
anchor_counter = "9gAhhkLjGeKyb2NGPF4rU6WRbrXotVzZPfqq4pvmbRJ7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/tarun/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
